# Generated by Django 3.0.7 on 2020-06-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='harmonizacao',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='history',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='premios',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
