# Generated by Django 3.0.7 on 2020-06-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200615_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='harmonizacao',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='history',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='premios',
            field=models.TextField(null=True),
        ),
    ]
